### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by binarious** [ly95/vsc.phpmd#16]
I get the following error while typing into any PHP document:
```
[Error - 13:00:20] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
```
The extension does work though, but sometimes it isn't updating:

<img width="736" alt="commoncontroller_php_-_smt" src="https://cloud.githubusercontent.com/assets/200375/22736529/d60f48ac-edfe-11e6-9e9d-5363bca03da5.png">

Code: 1.9.0
macOS: 10.12.3
phpmd Ext: 1.1.3
phpmd: 2.6.0
PHP: 7.0.15

**Comment by us3r64** [comment]
Getting same error in OUTPUT:

```
Error - 7:38:19 PM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601
```

phpmd Ext: 1.1.3
phpmd: 2.6.0
