### ISSUE TITLE
为什么不把phpcs.phar文件放在你自己的扩展目录中一起发布

### ISSUE THREAD

**Issue by guodf** [ly95/vsc.phpmd#2]
如果这样做，我们只需要安装php就可以了。
另一个原因：phpcs.phar如果有更新，那么你的vscode扩展插件phpcs也需要跟着更新，既然这样，那么把phpcs.phar和你的vscode扩展插件phpcs一起发布不是更好吗？！

**Comment by ly95** [comment]
谢谢您提供的建议，已加入下一个版本计划 😄
