### ISSUE TITLE
Use vscode-language-server

### ISSUE THREAD

**Issue by mizunashi-mana** [ly95/vsc.phpmd#7]
Now, this extension is stand alone.
But, it causes low performance and extensibility.

We should use [vscode-language-server](https://github.com/Microsoft/vscode-languageserver-node).

What about this?

**Comment by ly95** [comment]
I am already work on this.

**Comment by mizunashi-mana** [comment]
Oh, thanks!

But, I would like you to leave this issue opened until being fixed for my remember.
If you says ok, I reopen this issue.

**Comment by ly95** [comment]
It's ok

**Comment by mizunashi-mana** [comment]
@ly95 thanks!

**Comment by ly95** [comment]
The new version (v1.0.0) has been released.

**Comment by mizunashi-mana** [comment]
@ly95 thanks!
