### ISSUE TITLE
Add Composer support

### ISSUE THREAD

**Issue by mizunashi-mana** [ly95/vsc.phpmd#8]
[Composer](https://getcomposer.org/) is the modern PHP package manager.

In some cases, it installs `phpmd` on project local(./vendor/bin).
If `./vendor/bin/phpmd` exists, I want to use this one.

**Comment by ly95** [comment]
Version 0.3.1

**Comment by SidIcarus** [comment]
Currently the default settings has the executable path set to: "phpmd"
Does the extension automatically detect if composer is being used or not? Or do we need to set it to "./vendor/bin/phpmd" or "./vendor/bin/"?

**Comment by ly95** [comment]
you can set absolute executable path like this:

```json
"phpmd.validate.executablePath": "/usr/bin/phpmd"
```
